/*
 * runs.c
 * 
 * Copyright 2014 aman <aman@aman-Aspire-4750>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */


#include <stdio.h>
#include <string.h>
#include <math.h>
#include "flint/fmpz.h"

static double errorFunction(double x)
{
	double p = 0.3275911;
	double a1 = 0.254829592;
	double a2 = -0.284496736;
	double a3 = 1.421413741;
	double a4 = -1.453152027;
	double a5 = 1.061405429;
	double t = 1.0 / (1.0 + p * x);
	 
	double err = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * exp(-x * x);
		
	return err;
}

static double errorFunctionComplement(double x)
{
	return 1 - errorFunction(x);
}

static double runsTest(char *string)
{
	double numOnes = 0.0;
	
	int i;
	for(i = 0; i < strlen(string); i++) {
		if(string[i] == '1') {
			numOnes++;
		}
	}
	
	double prop = (numOnes * 1.0) / strlen(string);
	int runs = 1;
	
	for(i = 0; i < strlen(string) - 1; i++) {
		if(string[i] != string[i+1]) {
			runs++;
		}
	}
		
	double num = fabs(runs - (2 * strlen(string) * prop * (1 - prop)));
	double denom = 2 * sqrt(2.0 * strlen(string)) * prop * (1 - prop);
		
	double pValue = errorFunctionComplement(num / denom);
	return pValue;
}

int main(int argc, char **argv)
{
	printf("Beginning runs test for random numbers generated by the randm function of fmpz module\n");
	
	fmpz_t f, m;
	flint_rand_t state;
	fmpz_init(f);
	fmpz_init_set_ui(m, 2);
	flint_randinit(state);
	char *str;
	char *bitString = malloc(10000);
	int i;
	for(i = 0; i < 10000; i++) {
		str = NULL;
		fmpz_randm(f, state, m);
		strcat(bitString, (str=fmpz_get_str(str, 10, f)));
		free(str);
	}
	fmpz_clear(f);
	fmpz_clear(m);
	flint_randclear(state);
	
	printf("Input sequence to test for randomness:\n");
	printf("%s\n", bitString);
	
	printf("Testing input runs\n");
	double pRuns = runsTest(bitString);
	printf("pValue for runs test = %f\n", pRuns);
	
	if(pRuns < 0.01) {
		printf("There is evidence that the sequence is not random\n");
	} else {
		printf("Sequence passes runs test for randomness\n");
	}
	
	free(bitString);
	
	return 0;
}

